[package]
name = "zenlang-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
zenlang = { version = "0.1.0", path = "../zenlang" }
zenlang-platform-std = { version = "0.1.0", path = "../zenlang-platform-std" }
