name: Rust docs

on:
  push:
    paths:
      - 'zenlang/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    paths:
      - 'zenlang/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      
env:
  CARGO_TERM_COLOR: always

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Download rust toolchain
        run: |
          rustup default stable

      - name: Build documentation
        run: |
          cargo build
          cargo doc
          echo '<meta http-equiv="refresh" content="0;url=zenlang/index.html">' > target/doc/index.html
          cp target/doc/zenlang/ ./docs -r
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs/'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
